import Foundation

enum TokenStepLocalization {
    private(set) static var selectedLanguage: TokenStepLanguage = .system

    static var language: TokenStepLanguage {
        selectedLanguage.resolved
    }

    static var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    static func apply(_ language: TokenStepLanguage) {
        selectedLanguage = language
    }

    static func text(_ key: String) -> String {
        guard language != .zhHans else { return key }
        return translations[language]?[key] ?? key
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        format(key, arguments)
    }

    static func format(_ key: String, _ arguments: [CVarArg]) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    private static let translations: [TokenStepLanguage: [String: String]] = [
        .en: [
            "自动": "Auto",
            "刘海左侧": "Left of notch",
            "刘海右侧": "Right of notch",
            "菜单栏": "Menu bar",
            "左侧": "Left",
            "右侧": "Right",
            "跟随系统": "Follow System",
            "自动匹配 macOS": "Match macOS",
            "准备更新": "Preparing update",
            "正在下载": "Downloading",
            "正在安装并重启": "Installing and relaunching",
            "更新失败": "Update failed",
            "菜单栏模式": "Menu bar mode",
            "自动：刘海旁": "Auto: beside notch",
            "自动：菜单栏": "Auto: menu bar",
            "鼠标移入后展开浮层": "Hover to expand",
            "仅使用右上角菜单栏入口": "Use menu bar only",
            "刷新": "Refresh",
            "打开 TokenStep": "Open TokenStep",
            "设置": "Settings",
            "等待同步": "Waiting to sync",
            "手动": "Manual",
            "%d 分钟": "%d min",
            "1 分钟": "1 min",
            "第 %d 圈": "Lap %d",
            "第 %d 圈 · %@": "Lap %d · %@",
            "已完成 %d 圈": "%d laps completed",
            "已完成 %@": "%@ completed",
            "每圈目标 %@": "%@ per lap",
            "少": "Less",
            "多": "More",
            "活跃": "Active",
            "达标": "Goal",
            "最高": "Best",
            "近 8 个月活动墙": "Last 8 Months",
            "颜色越深，越接近或超过每日目标": "Darker means closer to, or beyond, the daily goal",
            "%d 个活跃日": "%d active days",
            "全部明细": "All Details",
            "%d 条记录，向下滚动查看完整历史": "%d records. Scroll down for full history",
            "最近 %d 天，适合保存为截图": "Last %d days, ready for screenshots",
            "日期": "Date",
            "Token 消耗": "Token Usage",
            "消耗金额": "Cost",
            "主力工具": "Main Tool",
            "无": "None",
            "累计 Token 消耗": "Total Token Usage",
            "等待下一次同步": "Waiting for next sync",
            "最近 30 天": "Last 30 Days",
            "颜色越深，圈数越高": "Darker means a higher lap",
            "今天 %@": "Today %@",
            "/ %@ 每圈": "/ %@ per lap",
            "圈数进度": "Lap Progress",
            "按客户端": "By Client",
            "按模型": "By Model",
            "累计总量分布": "Total distribution",
            "主力模型": "Top Models",
            "本月均值": "Monthly Avg",
            "活跃天数": "Active Days",
            "达标天数": "Goal Days",
            "有 AI 使用的日期": "Days with AI usage",
            "达到每日目标": "Reached daily goal",
            "%d圈完成": "Lap %d done",
            "%@进行中": "%@ in progress",
            "所有本机记录": "All local records",
            "今日": "Today",
            "历史": "History",
            "统计": "Analytics",
            "模型与工具": "Models & Tools",
            "隐私": "Privacy",
            "今日消耗": "Today",
            "历史活动": "History",
            "用量统计": "Analytics",
            "今天的 Token 使用节奏": "Today’s token rhythm",
            "长期节奏和所有历史记录": "Long-term rhythm and all history",
            "按客户端和模型拆开看": "Break down by client and model",
            "只统计数量，不读取内容": "Only counts usage, never reads content",
            "保存当前页 PNG（最近 30 天）": "Save Page PNG (Last 30 Days)",
            "保存当前页 PNG": "Save Page PNG",
            "复制当前页截图": "Copy Page Screenshot",
            "截取当前页": "Capture Page",
            "更新": "Updated",
            "同步中": "Syncing",
            "已同步": "Synced",
            "每天一个亿": "100M a day",
            "本地统计": "Local Only",
            "不上传代码或对话": "No code or chats uploaded",
            "让 TokenStep 按你的节奏记录 Token 消耗": "Let TokenStep track token usage at your rhythm",
            "语言": "Language",
            "选择 TokenStep 的显示语言": "Choose how TokenStep speaks to you",
            "当前语言": "Current language",
            "切换后立即生效": "Changes apply immediately",
            "TokenStep · Local usage tracker": "TokenStep · Local usage tracker",
            "每日目标": "Daily Goal",
            "token / 天": "tokens / day",
            "自动刷新": "Auto Refresh",
            "显示入口": "Display Entry",
            "菜单栏、弹层和仪表盘会按这个频率同步更新。": "The menu bar, popover, and dashboard sync at this rhythm.",
            "手动更新": "Manual refresh",
            "每 %@": "Every %@",
            "当前节奏": "Current rhythm",
            "显示位置": "Display Position",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "On notch displays, show beside the notch. Otherwise use the menu bar.",
            "主题色": "Theme Color",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "The menu bar, rings, activity wall, and buttons follow the theme.",
            "当前主题": "Current theme",
            "登录后自动启动 TokenStep": "Launch TokenStep at login",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "Track quietly like steps, so daily token usage is not missed.",
            "自动更新": "Auto Update",
            "自动检查 TokenStep 新版本": "Check for TokenStep updates automatically",
            "有更新时先提醒你，下载前会确认。": "You will be notified first, and asked before downloading.",
            "检查中": "Checking",
            "检查更新": "Check Updates",
            "隐私状态": "Privacy Status",
            "本地隐私保护已开启": "Local privacy protection is on",
            "代码与对话不会离开这台 Mac": "Code and chats never leave this Mac",
            "恢复默认": "Reset Defaults",
            "完成": "Done",
            "可更新": "Update available",
            "正在检查": "Checking",
            "尚未检查": "Not checked yet",
            "当前版本 %@": "Current version %@",
            "发现 %@": "Found %@",
            "下载前询问": "Ask before download",
            "仅安装已签名公证版本": "Only install signed and notarized builds",
            "开机启动": "Launch at Login",
            "已开启": "On",
            "已关闭": "Off",
            "下次登录会自动运行": "Runs automatically next login",
            "需要手动启动 App": "Start the app manually",
            "不读取代码与对话": "Does not read code or chats",
            "不默认上传数据": "Does not upload by default",
            "本机": "This Mac",
            "%d 个客户端": "%d clients",
            "截取设置页": "Capture settings",
            "复制设置截图": "Copy settings screenshot",
            "保存设置 PNG": "Save settings PNG",
            "今日 Token 消耗": "Daily Token Usage",
            "每日 Token 消耗追踪": "Daily Token Tracking",
            "Codex 剩余额度": "Codex Quota",
            "Codex 额度显示": "Show Codex Quota",
            "5 小时": "5 hours",
            "7 天": "7 days",
            "剩余 %@": "%@ left",
            "等待重置": "Reset pending",
            "即将重置": "Resetting soon",
            "%d 分后重置": "Resets in %d min",
            "约 %d:%02d 后重置": "Resets in about %d:%02d",
            "%d 天后重置": "Resets in %d days",
            "刚刚": "Just now",
            "%d 分钟前": "%d min ago",
            "暂未读取到 Codex 额度": "Codex quota unavailable",
            "打开并登录 Codex 后会自动显示额度。": "Open and sign in to Codex to show quota automatically.",
            "复制浮层截图": "Copy popover screenshot",
            "保存浮层 PNG": "Save popover PNG",
            "截取浮层": "Capture popover",
            "细线是每日目标": "Thin line marks the daily goal",
            "手动刷新": "Manual refresh",
            "刷新 %@": "Refresh %@",
            "打开仪表盘": "Open Dashboard",
            "退出": "Quit",
            "青绿": "Green",
            "海蓝": "Ocean",
            "紫藤": "Violet",
            "琥珀": "Amber",
            "石墨": "Graphite",
            "默认": "Default",
            "清爽": "Fresh",
            "温暖": "Warm",
            "专注": "Focus",
            "发现新版本 %@": "New version %@ available",
            "内存占用优化与稳定性改进": "Memory and stability improvements",
            "立即更新": "Update Now",
            "稍后": "Later",
            "TokenStep %@ 可用": "TokenStep %@ Available",
            "安装完成后会自动重启到新版本": "TokenStep will relaunch after installation",
            "更新内容": "What’s New",
            "自动安装到 Applications": "Install to Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "After download, the app in the DMG is verified and replaces the old version",
            "跳过此版本": "Skip Version",
            "安装中": "Installing",
            "安装并重启": "Install & Relaunch",
            "优化 Codex 历史数据读取": "Improved Codex history reading",
            "降低后台刷新 CPU 占用": "Reduced background refresh CPU usage",
            "提升菜单栏同步稳定性": "Improved menu bar sync stability",
            "检查更新失败，请稍后再试。": "Could not check for updates. Please try again later.",
            "新版本没有可下载的 DMG。": "The new version has no downloadable DMG.",
            "下载更新失败，请稍后再试。": "Could not download the update. Please try again later.",
            "新版本未通过签名或公证验证，已停止安装。": "The new version did not pass signing or notarization checks.",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "Automatic install failed. Try again later, or drag TokenStep to Applications manually.",
            "只统计 token 数量": "Only counts token usage",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "Used for daily token usage, trends, and estimated cost.",
            "所有数据文件都保留在这台 Mac 上。": "All data files stay on this Mac.",
            "消耗金额仅供参考": "Cost is only an estimate",
            "按本地价格表粗略估算，不等于真实账单。": "Estimated locally and may not match your real bill.",
            "本地优先": "Local First",
            "本地文件": "Local Files",
            "用量数据": "Usage data",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "If leaderboard support is added later, it will require separate authorization.",
            "截图": "Screenshot",
            "复制截图": "Copy screenshot",
            "保存 PNG": "Save PNG",
            "TokenStep 更新": "TokenStep Update",
            "未检测到可用屏幕": "No available display detected",
            "当前主屏无刘海，已回到菜单栏": "The main display has no notch, so TokenStep is using the menu bar",
            "截图生成失败，请稍后再试。": "Could not create the screenshot. Please try again later.",
            "PNG 文件生成失败，请稍后再试。": "Could not create the PNG file. Please try again later.",
            "采集脚本退出码 %d": "Collector exited with code %d",
            "采集脚本退出码 %d：%@": "Collector exited with code %d: %@",
            "切换到%@主题": "Switch to %@ theme",
            "TokenStep 自动更新失败": "TokenStep Auto Update Failed",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "Please drag TokenStep from the DMG into Applications manually.",
        ],
        .zhHant: [
            "简体中文": "簡體中文",
            "自动": "自動",
            "刘海左侧": "瀏海左側",
            "刘海右侧": "瀏海右側",
            "菜单栏": "選單列",
            "左侧": "左側",
            "右侧": "右側",
            "跟随系统": "跟隨系統",
            "自动匹配 macOS": "自動匹配 macOS",
            "准备更新": "準備更新",
            "正在下载": "正在下載",
            "正在安装并重启": "正在安裝並重新啟動",
            "更新失败": "更新失敗",
            "菜单栏模式": "選單列模式",
            "自动：刘海旁": "自動：瀏海旁",
            "自动：菜单栏": "自動：選單列",
            "鼠标移入后展开浮层": "滑鼠移入後展開浮層",
            "仅使用右上角菜单栏入口": "僅使用右上角選單列入口",
            "刷新": "重新整理",
            "打开 TokenStep": "開啟 TokenStep",
            "设置": "設定",
            "等待同步": "等待同步",
            "手动": "手動",
            "%d 分钟": "%d 分鐘",
            "1 分钟": "1 分鐘",
            "第 %d 圈": "第 %d 圈",
            "第 %d 圈 · %@": "第 %d 圈 · %@",
            "已完成 %d 圈": "已完成 %d 圈",
            "已完成 %@": "已完成 %@",
            "每圈目标 %@": "每圈目標 %@",
            "少": "少",
            "多": "多",
            "活跃": "活躍",
            "达标": "達標",
            "最高": "最高",
            "近 8 个月活动墙": "近 8 個月活動牆",
            "颜色越深，越接近或超过每日目标": "顏色越深，越接近或超過每日目標",
            "%d 个活跃日": "%d 個活躍日",
            "全部明细": "全部明細",
            "%d 条记录，向下滚动查看完整历史": "%d 條記錄，向下捲動查看完整歷史",
            "最近 %d 天，适合保存为截图": "最近 %d 天，適合儲存為截圖",
            "日期": "日期",
            "Token 消耗": "Token 消耗",
            "消耗金额": "消耗金額",
            "主力工具": "主力工具",
            "无": "無",
            "累计 Token 消耗": "累計 Token 消耗",
            "等待下一次同步": "等待下一次同步",
            "最近 30 天": "最近 30 天",
            "颜色越深，圈数越高": "顏色越深，圈數越高",
            "今天 %@": "今天 %@",
            "/ %@ 每圈": "/ %@ 每圈",
            "圈数进度": "圈數進度",
            "按客户端": "按客戶端",
            "按模型": "按模型",
            "累计总量分布": "累計總量分布",
            "主力模型": "主力模型",
            "本月均值": "本月均值",
            "活跃天数": "活躍天數",
            "达标天数": "達標天數",
            "有 AI 使用的日期": "有 AI 使用的日期",
            "达到每日目标": "達到每日目標",
            "%d圈完成": "%d圈完成",
            "%@进行中": "%@進行中",
            "所有本机记录": "所有本機記錄",
            "今日": "今日",
            "历史": "歷史",
            "统计": "統計",
            "模型与工具": "模型與工具",
            "隐私": "隱私",
            "今日消耗": "今日消耗",
            "历史活动": "歷史活動",
            "用量统计": "用量統計",
            "今天的 Token 使用节奏": "今天的 Token 使用節奏",
            "长期节奏和所有历史记录": "長期節奏和所有歷史記錄",
            "按客户端和模型拆开看": "按客戶端和模型拆開看",
            "只统计数量，不读取内容": "只統計數量，不讀取內容",
            "保存当前页 PNG（最近 30 天）": "儲存目前頁 PNG（最近 30 天）",
            "保存当前页 PNG": "儲存目前頁 PNG",
            "复制当前页截图": "複製目前頁截圖",
            "截取当前页": "擷取目前頁",
            "更新": "更新",
            "同步中": "同步中",
            "已同步": "已同步",
            "每天一个亿": "每天一個億",
            "本地统计": "本地統計",
            "不上传代码或对话": "不上傳程式碼或對話",
            "让 TokenStep 按你的节奏记录 Token 消耗": "讓 TokenStep 按你的節奏記錄 Token 消耗",
            "语言": "語言",
            "选择 TokenStep 的显示语言": "選擇 TokenStep 的顯示語言",
            "当前语言": "目前語言",
            "切换后立即生效": "切換後立即生效",
            "TokenStep · Local usage tracker": "TokenStep · 本地用量追蹤器",
            "每日目标": "每日目標",
            "token / 天": "token / 天",
            "自动刷新": "自動重新整理",
            "显示入口": "顯示入口",
            "菜单栏、弹层和仪表盘会按这个频率同步更新。": "選單列、浮層和儀表板會按這個頻率同步更新。",
            "手动更新": "手動更新",
            "每 %@": "每 %@",
            "当前节奏": "目前節奏",
            "显示位置": "顯示位置",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "瀏海螢幕顯示在瀏海旁，其他螢幕使用選單列。",
            "主题色": "主題色",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "選單列、圓環、活動牆和按鈕會一起跟隨主題變化。",
            "当前主题": "目前主題",
            "登录后自动启动 TokenStep": "登入後自動啟動 TokenStep",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "像步數一樣默默記錄，避免漏掉每天的 Token 消耗。",
            "自动更新": "自動更新",
            "自动检查 TokenStep 新版本": "自動檢查 TokenStep 新版本",
            "有更新时先提醒你，下载前会确认。": "有更新時先提醒你，下載前會確認。",
            "检查中": "檢查中",
            "检查更新": "檢查更新",
            "隐私状态": "隱私狀態",
            "本地隐私保护已开启": "本地隱私保護已開啟",
            "代码与对话不会离开这台 Mac": "程式碼與對話不會離開這台 Mac",
            "恢复默认": "恢復預設",
            "完成": "完成",
            "可更新": "可更新",
            "正在检查": "正在檢查",
            "尚未检查": "尚未檢查",
            "当前版本 %@": "目前版本 %@",
            "发现 %@": "發現 %@",
            "下载前询问": "下載前詢問",
            "仅安装已签名公证版本": "僅安裝已簽名公證版本",
            "开机启动": "開機啟動",
            "已开启": "已開啟",
            "已关闭": "已關閉",
            "下次登录会自动运行": "下次登入會自動執行",
            "需要手动启动 App": "需要手動啟動 App",
            "不读取代码与对话": "不讀取程式碼與對話",
            "不默认上传数据": "不預設上傳資料",
            "本机": "本機",
            "%d 个客户端": "%d 個客戶端",
            "截取设置页": "擷取設定頁",
            "复制设置截图": "複製設定截圖",
            "保存设置 PNG": "儲存設定 PNG",
            "今日 Token 消耗": "今日 Token 消耗",
            "每日 Token 消耗追踪": "每日 Token 消耗追蹤",
            "Codex 剩余额度": "Codex 剩餘額度",
            "Codex 额度显示": "顯示 Codex 額度",
            "5 小时": "5 小時",
            "7 天": "7 天",
            "剩余 %@": "剩餘 %@",
            "等待重置": "等待重置",
            "即将重置": "即將重置",
            "%d 分后重置": "%d 分後重置",
            "约 %d:%02d 后重置": "約 %d:%02d 後重置",
            "%d 天后重置": "%d 天後重置",
            "刚刚": "剛剛",
            "%d 分钟前": "%d 分鐘前",
            "暂未读取到 Codex 额度": "暫未讀取到 Codex 額度",
            "打开并登录 Codex 后会自动显示额度。": "開啟並登入 Codex 後會自動顯示額度。",
            "复制浮层截图": "複製浮層截圖",
            "保存浮层 PNG": "儲存浮層 PNG",
            "截取浮层": "擷取浮層",
            "细线是每日目标": "細線是每日目標",
            "手动刷新": "手動重新整理",
            "刷新 %@": "重新整理 %@",
            "打开仪表盘": "開啟儀表板",
            "退出": "退出",
            "青绿": "青綠",
            "海蓝": "海藍",
            "紫藤": "紫藤",
            "琥珀": "琥珀",
            "石墨": "石墨",
            "默认": "預設",
            "清爽": "清爽",
            "温暖": "溫暖",
            "专注": "專注",
            "发现新版本 %@": "發現新版本 %@",
            "内存占用优化与稳定性改进": "記憶體佔用最佳化與穩定性改進",
            "立即更新": "立即更新",
            "稍后": "稍後",
            "TokenStep %@ 可用": "TokenStep %@ 可用",
            "安装完成后会自动重启到新版本": "安裝完成後會自動重新啟動到新版本",
            "更新内容": "更新內容",
            "自动安装到 Applications": "自動安裝到 Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "下載後會驗證 DMG 中的 App，並替換舊版本",
            "跳过此版本": "略過此版本",
            "安装中": "安裝中",
            "安装并重启": "安裝並重新啟動",
            "优化 Codex 历史数据读取": "最佳化 Codex 歷史資料讀取",
            "降低后台刷新 CPU 占用": "降低背景重新整理 CPU 佔用",
            "提升菜单栏同步稳定性": "提升選單列同步穩定性",
            "检查更新失败，请稍后再试。": "檢查更新失敗，請稍後再試。",
            "新版本没有可下载的 DMG。": "新版本沒有可下載的 DMG。",
            "下载更新失败，请稍后再试。": "下載更新失敗，請稍後再試。",
            "新版本未通过签名或公证验证，已停止安装。": "新版本未通過簽名或公證驗證，已停止安裝。",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "自動安裝失敗，請稍後重試，或手動把 TokenStep 拖到 Applications。",
            "只统计 token 数量": "只統計 token 數量",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "用於計算今日 Token 消耗、歷史趨勢和消耗金額。",
            "所有数据文件都保留在这台 Mac 上。": "所有資料檔案都保留在這台 Mac 上。",
            "消耗金额仅供参考": "消耗金額僅供參考",
            "按本地价格表粗略估算，不等于真实账单。": "按本地價格表粗略估算，不等於真實帳單。",
            "本地优先": "本地優先",
            "本地文件": "本地檔案",
            "用量数据": "用量資料",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "後續如果接入排行榜，會單獨做授權和確認，不會預設上傳。",
            "截图": "截圖",
            "复制截图": "複製截圖",
            "保存 PNG": "儲存 PNG",
            "TokenStep 更新": "TokenStep 更新",
            "未检测到可用屏幕": "未偵測到可用螢幕",
            "当前主屏无刘海，已回到菜单栏": "目前主螢幕無瀏海，已回到選單列",
            "截图生成失败，请稍后再试。": "截圖產生失敗，請稍後再試。",
            "PNG 文件生成失败，请稍后再试。": "PNG 檔案產生失敗，請稍後再試。",
            "采集脚本退出码 %d": "採集腳本退出碼 %d",
            "采集脚本退出码 %d：%@": "採集腳本退出碼 %d：%@",
            "切换到%@主题": "切換到%@主題",
            "TokenStep 自动更新失败": "TokenStep 自動更新失敗",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "請手動把 DMG 裡的 TokenStep 拖到 Applications。"
        ]
    ]
}

func L(_ key: String) -> String {
    TokenStepLocalization.text(key)
}

func LFormat(_ key: String, _ arguments: CVarArg...) -> String {
    TokenStepLocalization.format(key, arguments)
}
